version: "2"
services:
  fluentd:
    image:  xvjialing/fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./data:/fluentd/log
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"      

  elasticsearch:
    image: elasticsearch:5.6-alpine
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:5.6
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"